[alembic]
script_location = alembic

# ❗ Використовується тільки для offline-режиму
sqlalchemy.url = driver://placeholder


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = simple

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = simple

[formatter_simple]
format = %(levelname)s [%(name)s] %(message)s
