#domain/events.py

from enum import Enum

class EventType(str, Enum):
    CONTRACT_ACCEPTED = "CONTRACT_ACCEPTED"
    DATASET_BUILT = "DATASET_BUILT"
    DATASET_MATERIALIZED = "DATASET_MATERIALIZED"
    TRAIN_COMPLETED = "TRAIN_COMPLETED"
    EVAL_COMPLETED = "EVAL_COMPLETED"
    FAILED = "FAILED"